packages:
  - 'packages/*'
  - 'packages-private/*'

catalog:
  '@babel/parser': ^7.26.10
  '@babel/types': ^7.26.10
  'estree-walker': ^2.0.2
  'magic-string': ^0.30.17
  'source-map-js': ^1.2.1
  'vite': ^5.4.14
  '@vitejs/plugin-vue': ^5.2.2
