packages:
  - 'packages/*'
  - 'packages-private/*'

catalog:
  '@babel/parser': ^7.28.3
  '@babel/types': ^7.28.2
  'estree-walker': ^2.0.2
  'vite': ^6.1.0
  '@vitejs/plugin-vue': ^6.0.1
  'magic-string': ^0.30.17
  'source-map-js': ^1.2.1

onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'puppeteer'
  - 'simple-git-hooks'
  - 'unrs-resolver'

peerDependencyRules:
  allowedVersions:
    'typescript-eslint>eslint': '^9.0.0'
    '@typescript-eslint/eslint-plugin>eslint': '^9.0.0'
    '@typescript-eslint/parser>eslint': '^9.0.0'
    '@typescript-eslint/type-utils>eslint': '^9.0.0'
    '@typescript-eslint/utils>eslint': '^9.0.0'
