packages:
  - 'packages/*'
  - 'packages-private/*'

catalog:
  '@babel/parser': ^7.26.10
  '@babel/types': ^7.26.10
  'estree-walker': ^2.0.2
  'vite': ^6.1.0
  '@vitejs/plugin-vue': https://pkg.pr.new/@vitejs/plugin-vue@c156992
  'magic-string': ^0.30.17
  'source-map-js': ^1.2.1
