packages:
  - 'packages/*'
  - 'packages-private/*'

catalog:
  '@babel/parser': ^7.28.6
  '@babel/types': ^7.28.6
  'estree-walker': ^2.0.2
  'vite': ^8.0.0-beta.4
  '@vitejs/plugin-vue': ^6.0.3
  'magic-string': ^0.30.21
  'source-map-js': ^1.2.1

onlyBuiltDependencies:
  - '@swc/core'
  - 'puppeteer'
  - 'simple-git-hooks'
  - 'unrs-resolver'
