packages:
  - 'packages/*'
  - 'packages-private/*'

catalog:
  '@babel/parser': ^7.25.3
  '@babel/types': ^7.25.2
  'estree-walker': ^2.0.2
  'magic-string': ^0.30.11
  'source-map-js': ^1.2.0
  'vite': ^6.1.0
  '@vitejs/plugin-vue': https://pkg.pr.new/@vitejs/plugin-vue@c156992
