/**
 * Element tag → SwiftUI view mapping.
 * Keys are Vue spatial template tag names, values are SwiftUI view type names.
 */
export const ELEMENT_MAP: Record<string, string> = {
  'v-stack': 'VStack',
  'h-stack': 'HStack',
  'z-stack': 'ZStack',
  text: 'Text',
  button: 'Button',
  image: 'Image',
  'sf-symbol': 'Image',
  'text-field': 'TextField',
  toggle: 'Toggle',
  slider: 'Slider',
  list: 'List',
  'scroll-view': 'ScrollView',
  'navigation-stack': 'NavigationStack',
  'tab-view': 'TabView',
  label: 'Label',
  divider: 'Divider',
  spacer: 'Spacer',
  group: 'Group',
  model3d: 'Model3D',
  'reality-view': 'RealityView',
  'spatial-window': 'WindowGroup',
  'spatial-volume': 'WindowGroup',
  'spatial-immersive': 'ImmersiveSpace',
}

/**
 * Props that map to SwiftUI constructor arguments per element type.
 * e.g. VStack(spacing: 16, alignment: .leading)
 */
export const CONSTRUCTOR_PROPS: Record<string, Record<string, string>> = {
  VStack: { spacing: 'spacing', alignment: 'alignment' },
  HStack: { spacing: 'spacing', alignment: 'alignment' },
  ZStack: { alignment: 'alignment' },
  ScrollView: { axis: '' },
  WindowGroup: { title: '' },
  ImmersiveSpace: { id: 'id' },
}

/**
 * Props that map to SwiftUI view modifiers.
 * e.g. .font(.largeTitle), .opacity(0.7)
 */
export const MODIFIER_PROPS: Record<string, (value: string) => string> = {
  font: (v: string) => `.font(.${v})`,
  opacity: (v: string) => `.opacity(${v})`,
  disabled: (v: string) => `.disabled(${v})`,
  'foreground-color': (v: string) => `.foregroundStyle(.${v})`,
  'background-color': (v: string) => `.background(.${v})`,
}

/**
 * Spatial style property → SwiftUI modifier mapping.
 */
export const STYLE_MAP: Record<string, (value: string) => string> = {
  padding: (v: string) => `.padding(${v})`,
  'corner-radius': (v: string) =>
    `.clipShape(RoundedRectangle(cornerRadius: ${v}))`,
  'glass-background': (v: string) =>
    `.glassBackgroundEffect(in: .rect(cornerRadius: ${v === 'regular' ? '16' : v}))`,
  opacity: (v: string) => `.opacity(${v})`,
  'shadow-radius': (v: string) => `.shadow(radius: ${v})`,
  'frame-width': (v: string) => `.frame(width: ${v})`,
  'frame-height': (v: string) => `.frame(height: ${v})`,
  'foreground-color': (v: string) => `.foregroundStyle(.${v})`,
  'background-color': (v: string) => `.background(.${v})`,
  font: (v: string) => `.font(.${v})`,
  depth: (v: string) => `.offset(z: ${v})`,
  'hover-effect': (v: string) => `.hoverEffect(.${v})`,
}

/**
 * Generates the full SwiftUI View struct wrapping compiled body code.
 */
export function generateSwiftView(
  componentName: string,
  bodyLines: string[],
): string {
  const lines: string[] = []
  lines.push('// Auto-generated by @vue/compiler-spatial — do not edit')
  lines.push('import SwiftUI')
  lines.push('')
  lines.push(`struct ${componentName}: View {`)
  lines.push('    @ObservedObject var vm: VueViewModel')
  lines.push('')
  lines.push('    var body: some View {')
  for (const line of bodyLines) {
    lines.push('        ' + line)
  }
  lines.push('    }')
  lines.push('}')
  return lines.join('\n')
}

export interface BridgeManifest {
  component: string
  reactiveState: Record<string, { type: string; default?: unknown }>
  events: Record<string, { handler: string }>
  bindings: string[]
  spatialGestures: string[]
}

/**
 * Creates an empty bridge manifest for a component.
 */
export function createBridgeManifest(componentName: string): BridgeManifest {
  return {
    component: componentName,
    reactiveState: {},
    events: {},
    bindings: [],
    spatialGestures: [],
  }
}
