import type { RawSlots, Slots } from '../componentSlots'
import {
  type ContextualRenderFn,
  currentRenderingInstance,
  setCurrentRenderingInstance,
} from '../componentRenderContext'
import {
  Comment,
  Fragment,
  type VNode,
  type VNodeArrayChildren,
  VaporSlot,
  type VaporSlotOutlet,
  blockStack,
  closeBlock,
  createBlock,
  createVNode,
  isVNode,
  openBlock,
  rawVaporSlotKey,
} from '../vnode'
import {
  NOOP,
  PatchFlags,
  ShapeFlags,
  SlotFlags,
  extend,
  isSymbol,
} from '@vue/shared'
import { warn } from '../warning'
import { isAsyncWrapper } from '../apiAsyncComponent'
import type { ComponentInternalInstance, Data } from '../component'

export { rawVaporSlotKey }

/**
 * Invokes a VDOM slot fallback under the outlet owner that produced it, the
 * way `renderSlot` would have rendered it inline. Vapor interop invokes
 * fallbacks late, outside any render, so it passes the owner recorded on the
 * vapor slot vnode. Internal to vapor interop.
 */
export function invokeSlotFallback(
  fallback: () => VNodeArrayChildren,
  owner: ComponentInternalInstance | null | undefined,
): VNodeArrayChildren {
  if (!owner) return fallback()
  const prev = setCurrentRenderingInstance(owner)
  const prevStackSize = blockStack.length
  try {
    return fallback()
  } finally {
    // close blocks left dangling when the fallback throws mid-block (#15070)
    for (let i = blockStack.length; i > prevStackSize; i--) closeBlock()
    setCurrentRenderingInstance(prev)
  }
}

/**
 * Compiler runtime helper for rendering `<slot/>`
 * @private
 */
export function renderSlot(
  slots: Slots,
  name: string,
  // can be nullish: `v-bind` on a `<slot>` compiles to
  // `normalizeProps(guardReactiveProps(exp))`, and both helpers preserve
  // nullish values by design
  props?: Data | null,
  // this is not a user-facing function, so the fallback is always generated by
  // the compiler and guaranteed to be a function returning an array
  fallback?: () => VNodeArrayChildren,
  noSlotted?: boolean,
  branchKey?: PropertyKey,
): VNode {
  // normalize once so that the key lookups below and the slot function itself
  // always see an object. fresh object rather than EMPTY_OBJ because the
  // custom element branch mutates it
  if (props == null) props = {}

  let slot = slots[name]

  // vapor slots rendered in vdom
  const vaporSlot = slot && (slot as any)[rawVaporSlotKey]
  if (vaporSlot) {
    const ret = (openBlock(), createBlock(VaporSlot, props))
    ret.vs = {
      slot: vaporSlot,
      outlets: fallback
        ? [{ fallback, vdom: true, owner: currentRenderingInstance }]
        : undefined,
      innerIds: fallback ? [-1] : undefined,
    }
    if (!noSlotted && ret.scopeId) {
      ret.slotScopeIds = [ret.scopeId + '-s']
    }
    return ret
  }

  if (
    currentRenderingInstance &&
    (currentRenderingInstance.ce ||
      (currentRenderingInstance.parent &&
        isAsyncWrapper(currentRenderingInstance.parent) &&
        currentRenderingInstance.parent.ce))
  ) {
    const slotProps =
      branchKey != null && props.key == null
        ? extend({}, props, { key: branchKey })
        : props
    const hasProps = Object.keys(slotProps).length > 0
    // in custom element mode, render <slot/> as actual slot outlets
    // wrap it with a fragment because in shadowRoot: false mode the slot
    // element gets replaced by injected content
    if (name !== 'default') slotProps.name = name
    return (
      openBlock(),
      createBlock(
        Fragment,
        null,
        [createVNode('slot', slotProps, fallback && fallback())],
        hasProps ? PatchFlags.BAIL : PatchFlags.STABLE_FRAGMENT,
      )
    )
  }

  if (__DEV__ && slot && slot.length > 1) {
    warn(
      `SSR-optimized slot function detected in a non-SSR-optimized render ` +
        `function. You need to mark this component with $dynamic-slots in the ` +
        `parent template.`,
    )
    slot = () => []
  }

  // a compiled slot disables block tracking by default to avoid manual
  // invocation interfering with template-based block tracking, but in
  // `renderSlot` we can be sure that it's template-based so we can force
  // enable it.
  if (slot && (slot as ContextualRenderFn)._c) {
    ;(slot as ContextualRenderFn)._d = false
  }
  const prevStackSize = blockStack.length
  openBlock()
  let rendered: VNode
  try {
    const content = slot && slot(props)
    const validSlotContent = content && ensureValidVNode(content)

    // forwarded vapor slots resolve this outlet's fallback themselves
    const fallbackHost =
      fallback &&
      content &&
      currentRenderingInstance &&
      currentRenderingInstance.appContext.vapor &&
      attachVaporSlotOutlet(content, fallback)
    // a hosted outlet is one fragment, slots left or not: its content shows
    // on its own and stays in place as the host comes and goes
    const keyedContent = fallbackHost ? content : validSlotContent

    const slotKey =
      props.key ||
      branchKey ||
      // slot content array of a dynamic conditional slot may have a branch
      // key attached in the `createSlots` helper, respect that
      (keyedContent && (keyedContent as any).key)
    rendered = createBlock(
      Fragment,
      {
        key:
          (slotKey && !isSymbol(slotKey) ? slotKey : `_${name}`) +
          // #7256 force differentiate fallback content from actual content
          (!keyedContent && fallback ? '_fb' : ''),
      },
      fallbackHost
        ? content!.concat(fallbackHost)
        : validSlotContent || (fallback ? fallback() : []),
      // the fallback host comes and goes with the shape of the content
      !fallbackHost &&
        validSlotContent &&
        (slots as RawSlots)._ === SlotFlags.STABLE
        ? PatchFlags.STABLE_FRAGMENT
        : PatchFlags.BAIL,
    )
  } catch (err) {
    // close blocks left dangling when the slot throws mid-block
    // they would otherwise retain every vnode created afterwards (#15070)
    for (let i = blockStack.length; i > prevStackSize; i--) closeBlock()
    throw err
  } finally {
    if (slot && (slot as ContextualRenderFn)._c) {
      ;(slot as ContextualRenderFn)._d = true
    }
  }
  if (!noSlotted && rendered.scopeId) {
    rendered.slotScopeIds = [rendered.scopeId + '-s']
  }
  return rendered
}

export function ensureValidVNode(
  vnodes: VNodeArrayChildren,
): VNodeArrayChildren | null {
  return vnodes.some(child => {
    if (!isVNode(child)) return true
    if (child.type === Comment) return false
    if (
      child.type === Fragment &&
      !ensureValidVNode(child.children as VNodeArrayChildren)
    )
      return false
    return true
  })
    ? vnodes
    : null
}

/**
 * Hands a vdom outlet's fallback over to the vapor slots its content consists
 * of: recorded on the slot vnode when the content is structurally that one
 * slot, else on the returned host vnode, to append to the content, which owns
 * the fallback and shows it while every slot is empty. An outlet that can
 * hold several slots gets its host with none in it yet, as long as vapor
 * slots are forwarded to it: the fallback then never changes hands, and
 * instance, as slots come and go.
 */
function attachVaporSlotOutlet(
  content: VNodeArrayChildren,
  fallback: () => VNodeArrayChildren,
): VNode | undefined {
  if (!findVaporSlots(content)) return
  const owner = currentRenderingInstance
  const outlet = { fallback, vdom: true, owner }
  let host: VNode | undefined
  if (!severalSlots && foundSlots.length) {
    // a lone slot stays the one vnode exposing the fallback (`<Transition>`)
    recordOutlet(foundSlots[0], outlet)
  } else if (foundSlots.length || forwardsVaporSlots(owner)) {
    // no slot at all: a closed `v-if` branch or an empty list of them
    host = (openBlock(), createBlock(VaporSlot, { key: '_fb' }))
    host.vs = {
      // NOOP: a host has no slot, only the guards on `vs.slot` to pass
      slot: NOOP,
      outlets: [outlet],
      // a child of the outlet's own fragment
      innerIds: [0],
      members: foundSlots.slice(),
    }
    for (let i = 0; i < foundSlots.length; i++) foundSlots[i].vs!.hosted = true
  }
  foundSlots.length = 0
  return host
}

// whether the slots handed to this component forward vapor slots (marked by
// normalizeChildren)
const forwardsVaporSlots = (instance: ComponentInternalInstance | null) =>
  !!instance &&
  !!(instance.vnode.shapeFlag & ShapeFlags.SLOTS_CHILDREN) &&
  !!(instance.vnode.children as any)[rawVaporSlotKey]

/**
 * A vapor outlet rendering vdom slot content takes part only when that
 * content is structurally one vapor slot. Internal to vapor interop.
 */
export function recordVaporSlotOutlet(
  vnodes: VNodeArrayChildren,
  fallback: () => any,
): void {
  if (findVaporSlots(vnodes)) {
    if (!severalSlots && foundSlots.length) {
      recordOutlet(foundSlots[0], { fallback, vdom: false })
    }
    foundSlots.length = 0
  }
}

function recordOutlet(slot: VNode, outlet: VaporSlotOutlet): void {
  const vs = slot.vs!
  ;(vs.outlets ||= []).push(outlet)
  ;(vs.innerIds ||= []).push(pathIds)
}

// scratch for the walk below, which runs no user code and cannot re-enter
const foundSlots: VNode[] = []
let severalSlots = false
// slot scope ids of the fragments on the way to a lone slot (the renderer
// appends them in that order)
let pathIds = 0

// whether the content is made of vapor slots only, if any at all
function findVaporSlots(vnodes: VNodeArrayChildren): boolean {
  severalSlots = false
  pathIds = 0
  if (walkVaporSlots(vnodes)) return true
  foundSlots.length = 0
  return false
}

// Gathers the vapor slot vnodes in outlet content, looking through fragments
// and past comments the way `ensureValidVNode` does. False once valid vdom
// content is met: the outlet then stands on its own. `severalSlots` unless
// the content can never hold more than one slot: no siblings (a `v-if` leaves
// its comment behind) and no list on the way to it.
function walkVaporSlots(vnodes: VNodeArrayChildren): boolean {
  if (vnodes.length > 1) severalSlots = true
  for (let i = 0; i < vnodes.length; i++) {
    const child = vnodes[i]
    if (!isVNode(child)) return false
    if (child.vs) {
      foundSlots.push(child)
    } else if (child.type === Fragment) {
      if (
        child.patchFlag > 0 &&
        child.patchFlag &
          (PatchFlags.KEYED_FRAGMENT | PatchFlags.UNKEYED_FRAGMENT)
      ) {
        severalSlots = true
      }
      if (child.slotScopeIds) pathIds += child.slotScopeIds.length
      if (!walkVaporSlots(child.children as VNodeArrayChildren)) return false
    } else if (child.type !== Comment) {
      return false
    }
  }
  return true
}
