import type { RawSlots, Slots } from '../componentSlots'
import {
  type ContextualRenderFn,
  currentRenderingInstance,
  setCurrentRenderingInstance,
} from '../componentRenderContext'
import {
  Comment,
  Fragment,
  type VNode,
  type VNodeArrayChildren,
  VaporSlot,
  blockStack,
  closeBlock,
  createBlock,
  createVNode,
  isVNode,
  openBlock,
} from '../vnode'
import { NOOP, PatchFlags, SlotFlags, extend, isSymbol } from '@vue/shared'
import { warn } from '../warning'
import { isAsyncWrapper } from '../apiAsyncComponent'
import type { ComponentInternalInstance, Data } from '../component'

/**
 * Links a slot function to its raw vapor slot: a raw vapor slot carries
 * itself, and the wrapper the interop slots proxy hands out carries the raw
 * slot it wraps — one lookup answers both "is this a vapor slot" and
 * "which one". Internal to vapor interop.
 */
export const rawVaporSlotKey: unique symbol = Symbol(`rawVaporSlot`)

/**
 * Invokes a VDOM slot fallback under the outlet owner that produced it, the
 * way `renderSlot` would have rendered it inline. Vapor interop invokes
 * fallbacks late, outside any render, so it passes the owner recorded on the
 * vapor slot vnode. Internal to vapor interop.
 */
export function invokeSlotFallback(
  fallback: () => VNodeArrayChildren,
  owner: ComponentInternalInstance | null | undefined,
): VNodeArrayChildren {
  if (!owner) return fallback()
  const prev = setCurrentRenderingInstance(owner)
  const prevStackSize = blockStack.length
  try {
    return fallback()
  } finally {
    // close blocks left dangling when the fallback throws mid-block (#15070)
    for (let i = blockStack.length; i > prevStackSize; i--) closeBlock()
    setCurrentRenderingInstance(prev)
  }
}

/**
 * Compiler runtime helper for rendering `<slot/>`
 * @private
 */
export function renderSlot(
  slots: Slots,
  name: string,
  // can be nullish: `v-bind` on a `<slot>` compiles to
  // `normalizeProps(guardReactiveProps(exp))`, and both helpers preserve
  // nullish values by design
  props?: Data | null,
  // this is not a user-facing function, so the fallback is always generated by
  // the compiler and guaranteed to be a function returning an array
  fallback?: () => VNodeArrayChildren,
  noSlotted?: boolean,
  branchKey?: PropertyKey,
): VNode {
  // normalize once so that the key lookups below and the slot function itself
  // always see an object. fresh object rather than EMPTY_OBJ because the
  // custom element branch mutates it
  if (props == null) props = {}

  let slot = slots[name]

  // vapor slots rendered in vdom
  const vaporSlot = slot && (slot as any)[rawVaporSlotKey]
  if (vaporSlot) {
    const ret = (openBlock(), createBlock(VaporSlot, props))
    ret.vs = {
      slot: vaporSlot,
      outlets: fallback
        ? [{ fallback, vdom: true, owner: currentRenderingInstance }]
        : undefined,
    }
    if (!noSlotted && ret.scopeId) {
      ret.slotScopeIds = [ret.scopeId + '-s']
    }
    return ret
  }

  if (
    currentRenderingInstance &&
    (currentRenderingInstance.ce ||
      (currentRenderingInstance.parent &&
        isAsyncWrapper(currentRenderingInstance.parent) &&
        currentRenderingInstance.parent.ce))
  ) {
    const slotProps =
      branchKey != null && props.key == null
        ? extend({}, props, { key: branchKey })
        : props
    const hasProps = Object.keys(slotProps).length > 0
    // in custom element mode, render <slot/> as actual slot outlets
    // wrap it with a fragment because in shadowRoot: false mode the slot
    // element gets replaced by injected content
    if (name !== 'default') slotProps.name = name
    return (
      openBlock(),
      createBlock(
        Fragment,
        null,
        [createVNode('slot', slotProps, fallback && fallback())],
        hasProps ? PatchFlags.BAIL : PatchFlags.STABLE_FRAGMENT,
      )
    )
  }

  if (__DEV__ && slot && slot.length > 1) {
    warn(
      `SSR-optimized slot function detected in a non-SSR-optimized render ` +
        `function. You need to mark this component with $dynamic-slots in the ` +
        `parent template.`,
    )
    slot = () => []
  }

  // a compiled slot disables block tracking by default to avoid manual
  // invocation interfering with template-based block tracking, but in
  // `renderSlot` we can be sure that it's template-based so we can force
  // enable it.
  if (slot && (slot as ContextualRenderFn)._c) {
    ;(slot as ContextualRenderFn)._d = false
  }
  const prevStackSize = blockStack.length
  openBlock()
  let rendered: VNode
  try {
    const content = slot && slot(props)
    const validSlotContent = content && ensureValidVNode(content)

    // forwarded vapor slots resolve this outlet's fallback themselves
    const fallbackHost =
      fallback &&
      content &&
      attachVaporSlotOutlet(
        content,
        !!validSlotContent,
        fallback,
        props.key || branchKey || name,
      )
    // a host keeps the outlet's identity whether or not slots are left
    const keyedContent = fallbackHost ? content : validSlotContent

    const slotKey =
      props.key ||
      branchKey ||
      // slot content array of a dynamic conditional slot may have a branch
      // key attached in the `createSlots` helper, respect that
      (keyedContent && (keyedContent as any).key)
    rendered = createBlock(
      Fragment,
      {
        key:
          (slotKey && !isSymbol(slotKey) ? slotKey : `_${name}`) +
          // #7256 force differentiate fallback content from actual content
          (!keyedContent && fallback ? '_fb' : ''),
      },
      fallbackHost
        ? content!.concat(fallbackHost)
        : validSlotContent || (fallback ? fallback() : []),
      // the fallback host comes and goes with the shape of the content
      !fallbackHost &&
        validSlotContent &&
        (slots as RawSlots)._ === SlotFlags.STABLE
        ? PatchFlags.STABLE_FRAGMENT
        : PatchFlags.BAIL,
    )
  } catch (err) {
    // close blocks left dangling when the slot throws mid-block
    // they would otherwise retain every vnode created afterwards (#15070)
    for (let i = blockStack.length; i > prevStackSize; i--) closeBlock()
    throw err
  } finally {
    if (slot && (slot as ContextualRenderFn)._c) {
      ;(slot as ContextualRenderFn)._d = true
    }
  }
  if (!noSlotted && rendered.scopeId) {
    rendered.slotScopeIds = [rendered.scopeId + '-s']
  }
  return rendered
}

export function ensureValidVNode(
  vnodes: VNodeArrayChildren,
): VNodeArrayChildren | null {
  return vnodes.some(child => {
    if (!isVNode(child)) return true
    if (child.type === Comment) return false
    if (
      child.type === Fragment &&
      !ensureValidVNode(child.children as VNodeArrayChildren)
    )
      return false
    return true
  })
    ? vnodes
    : null
}

// outlets that got a fallback host, by owner: they keep it once no slot is left
const hostedOutlets = new WeakMap<object, Set<unknown>>()
let hasHostedOutlets = false

/**
 * Hands a vdom outlet's fallback over to the vapor slots its content consists
 * of: recorded on the slot vnode when the content is structurally that one
 * slot, else on the returned host vnode, to append to the content, which owns
 * the fallback and shows it while every slot is empty. An outlet keeps its
 * host while it holds no slot at all, so that the fallback does not change
 * hands, and instance, as slots come and go.
 */
function attachVaporSlotOutlet(
  content: VNodeArrayChildren,
  valid: boolean,
  fallback: () => VNodeArrayChildren,
  id: unknown,
): VNode | undefined {
  const owner = currentRenderingInstance
  if (valid) {
    if (!findVaporSlots(content)) return
  } else if (
    !hasHostedOutlets ||
    !owner ||
    !hostedOutlets.has(owner) ||
    !hostedOutlets.get(owner)!.has(id)
  ) {
    return
  }
  const outlet = { fallback, vdom: true, owner }
  let host: VNode | undefined
  if (!valid || severalSlots) {
    host = (openBlock(), createBlock(VaporSlot, { key: '_fb' }))
    // NOOP: a host has no slot, only the guards on `vs.slot` to pass
    host.vs = { slot: NOOP, outlets: [outlet], members: foundSlots.slice() }
    if (valid && owner) {
      let ids = hostedOutlets.get(owner)
      if (!ids) hostedOutlets.set(owner, (ids = new Set()))
      ids.add(id)
      hasHostedOutlets = true
    }
  } else {
    ;(foundSlots[0].vs!.outlets ||= []).push(outlet)
  }
  foundSlots.length = 0
  return host
}

/**
 * A vapor outlet rendering vdom slot content takes part only when that
 * content is structurally one vapor slot. Internal to vapor interop.
 */
export function recordVaporSlotOutlet(
  vnodes: VNodeArrayChildren,
  fallback: () => any,
): void {
  if (findVaporSlots(vnodes)) {
    if (!severalSlots) {
      ;(foundSlots[0].vs!.outlets ||= []).push({ fallback, vdom: false })
    }
    foundSlots.length = 0
  }
}

// scratch for the walk below, which runs no user code and cannot re-enter
const foundSlots: VNode[] = []
let severalSlots = false

function findVaporSlots(vnodes: VNodeArrayChildren): boolean {
  severalSlots = false
  if (walkVaporSlots(vnodes) && foundSlots.length) return true
  foundSlots.length = 0
  return false
}

// Gathers the vapor slot vnodes in outlet content, looking through fragments
// and past comments the way `ensureValidVNode` does. False once valid vdom
// content is met: the outlet then stands on its own. `severalSlots` unless
// the content can never hold more than one slot: no siblings (a `v-if` leaves
// its comment behind) and no list on the way to it.
function walkVaporSlots(vnodes: VNodeArrayChildren): boolean {
  if (vnodes.length > 1) severalSlots = true
  for (let i = 0; i < vnodes.length; i++) {
    const child = vnodes[i]
    if (!isVNode(child)) return false
    if (child.vs) {
      foundSlots.push(child)
    } else if (child.type === Fragment) {
      if (
        child.patchFlag > 0 &&
        child.patchFlag &
          (PatchFlags.KEYED_FRAGMENT | PatchFlags.UNKEYED_FRAGMENT)
      ) {
        severalSlots = true
      }
      if (!walkVaporSlots(child.children as VNodeArrayChildren)) return false
    } else if (child.type !== Comment) {
      return false
    }
  }
  return true
}
