import { describe, expect, test } from 'vitest'
import { getSwift } from './utils'

describe('spatial: full codegen', () => {
  test('generates complete SwiftUI View struct', () => {
    const swift = getSwift(
      `<v-stack spacing="16"><text font="largeTitle">Hello</text></v-stack>`,
      'HelloVisionOS',
    )
    expect(swift).toContain('// Auto-generated by @vue/compiler-spatial')
    expect(swift).toContain('import SwiftUI')
    expect(swift).toContain('struct HelloVisionOS: View {')
    expect(swift).toContain('@ObservedObject var vm: VueViewModel')
    expect(swift).toContain('var body: some View {')
    expect(swift).toContain('VStack(spacing: 16)')
    expect(swift).toContain('Text("Hello")')
    expect(swift).toContain('.font(.largeTitle)')
  })

  test('basic example from RFC', () => {
    const swift = getSwift(
      `<spatial-window title="Hello visionOS">
        <v-stack spacing="16">
          <text font="largeTitle">Hello</text>
          <button @tap="count++">
            <label>
              <text>Increment</text>
              <sf-symbol name="plus.circle.fill" />
            </label>
          </button>
        </v-stack>
      </spatial-window>`,
      'HelloVisionOS',
    )
    expect(swift).toContain('WindowGroup("Hello visionOS")')
    expect(swift).toContain('VStack(spacing: 16)')
    expect(swift).toContain('Text("Hello")')
    expect(swift).toContain('.font(.largeTitle)')
    expect(swift).toContain('Button(action:')
    expect(swift).toContain('Label {')
    expect(swift).toContain('Image(systemName: "plus.circle.fill")')
  })

  test('spatial-volume generates .windowStyle(.volumetric)', () => {
    const swift = getSwift(
      `<spatial-volume><text>3D content</text></spatial-volume>`,
    )
    expect(swift).toContain('WindowGroup')
    expect(swift).toContain('.windowStyle(.volumetric)')
  })

  test('immersive space', () => {
    const swift = getSwift(
      `<spatial-immersive id="immersive"><model3d src="earth.usdz" /></spatial-immersive>`,
    )
    expect(swift).toContain('ImmersiveSpace(id: "immersive")')
    expect(swift).toContain('Model3D(named: "earth.usdz")')
  })
})
