import {
  EMPTY_ARR,
  EMPTY_OBJ,
  NO,
  camelize,
  hasChanged,
  hasOwn,
  isArray,
  isFunction,
  isModelListener,
  isObject,
  isOn,
  isPlainObject,
  isReservedProp,
  isString,
  normalizeClass,
  normalizeStyle,
} from '@vue/shared'
import type { VaporComponent, VaporComponentInstance } from './component'
import {
  type NormalizedPropsOptions,
  baseNormalizePropsOptions,
  currentInstance,
  isEmitListener,
  popWarningContext,
  pushWarningContext,
  resolvePropValue,
  restoreCurrentInstance,
  setCurrentInstance,
  validateProps,
  warn,
} from '@vue/runtime-dom'
import {
  type ComputedRef,
  EffectFlags,
  ITERATE_KEY,
  ReactiveFlags,
  TrackOpTypes,
  TriggerOpTypes,
  computed,
  getCurrentScope,
  onScopeDispose,
  setActiveSub,
  track,
  trigger,
} from '@vue/reactivity'
import { normalizeEmitsOptions } from './componentEmits'
import { RenderEffect } from './renderEffect'
import { interopKey, isInteropEnabled } from './vdomInteropState'

export type RawProps = Record<string, unknown> & {
  // generated by compiler for :[key]="x" or v-bind="x"
  $?: DynamicPropsSource[] & { [interopKey]?: boolean }
}

export type DynamicPropsSource =
  | (() => Record<string, unknown>)
  | Record<string, unknown>

export function resolveSource<T>(source: T | (() => T)): T {
  return isFunction(source) ? resolveFunctionSource(source as () => T) : source
}

type FunctionSource<T> = (() => T) & {
  _cache?: ComputedRef<T>
}

export function resolveFunctionSource<T>(source: FunctionSource<T>): T {
  // use existing cache if available
  if (source._cache) {
    return source._cache.value
  }

  // source function is defined in the parent component, so it should be
  // executed in the parent's context. currentInstance is the child component
  // (the one accessing props/slots), so we use parent to get the component
  // where source was defined.
  const parent = currentInstance && currentInstance.parent
  if (parent) {
    // execute the source in the parent's context, but collect its cache in the
    // active consumer scope
    const prev = setCurrentInstance(parent, getCurrentScope())
    try {
      source._cache = computed(oldValue => {
        const prevInner = setCurrentInstance(parent)
        try {
          return stabilizeDynamicSourceValue(oldValue, source())
        } finally {
          restoreCurrentInstance(prevInner)
        }
      })
      onScopeDispose(() => (source._cache = undefined))
    } finally {
      restoreCurrentInstance(prev)
    }
    return source._cache.value
  }

  return source()
}

export function snapshotRawProps(rawProps: RawProps): RawProps {
  // Freeze the parent-provided raw source, not the child props proxy. This
  // keeps prop defaults lazy while preserving v-once input semantics.
  // Sources are read directly: the caller is the instance that defined them,
  // and a one-time read has no use for the computed `resolveFunctionSource`
  // would allocate. Values are stored plain; only a function value needs a
  // getter so readers do not invoke it.
  const snapshot: RawProps = Object.create(null)
  for (const key in rawProps) {
    if (key !== '$') {
      snapshot[key] = freezeValue(key, readSource(rawProps[key]))
    }
  }

  const dynamicSources = rawProps.$
  if (dynamicSources) {
    const snapshotSources: DynamicPropsSource[] & {
      [interopKey]?: boolean
    } = []
    for (let i = 0; i < dynamicSources.length; i++) {
      const source = dynamicSources[i]
      const isDynamic = isFunction(source)
      const resolved = readSource(source) || EMPTY_OBJ
      // Object sources are read without a per-source computed, so a resolved
      // function source is stored in that shape.
      const value: Record<string, unknown> = Object.create(null)
      for (const key in resolved) {
        value[key] = freezeValue(
          key,
          isDynamic ? resolved[key] : readSource(resolved[key]),
        )
      }
      snapshotSources[i] = value
    }
    const symbols = Object.getOwnPropertySymbols(dynamicSources)
    for (let i = 0; i < symbols.length; i++) {
      ;(snapshotSources as any)[symbols[i]] = (dynamicSources as any)[
        symbols[i]
      ]
    }
    snapshot.$ = snapshotSources
  }

  return snapshot
}

function readSource<T>(source: T | (() => T)): T {
  return isFunction(source) ? (source as () => T)() : source
}

function freezeValue(key: string, value: unknown): unknown {
  if (key === 'class' && value && !isString(value)) return normalizeClass(value)
  // wrapped so a lone (possibly reactive) style object is copied too
  if (key === 'style' && isObject(value)) return normalizeStyle([value])
  return isFunction(value) ? () => value : value
}

function stabilizeDynamicSourceValue<T>(oldValue: T | undefined, value: T): T {
  if (!isPlainObject(oldValue) || !isPlainObject(value)) {
    return value
  }

  // Dynamic sources often allocate a fresh object even when the resolved
  // props/attrs are unchanged. Keep the previous identity in that case so
  // computed consumers do not trigger child updates for equivalent values.
  const oldKeys = Object.keys(oldValue)
  const newKeys = Object.keys(value)
  if (oldKeys.length !== newKeys.length) {
    return value
  }

  for (let i = 0; i < newKeys.length; i++) {
    const key = newKeys[i]
    if (
      !hasOwn(oldValue, key) ||
      !Object.is((oldValue as any)[key], (value as any)[key])
    ) {
      return value
    }
  }

  return oldValue
}

export function getPropsProxyHandlers(
  comp: VaporComponent,
): [
  ProxyHandler<VaporComponentInstance> | null,
  ProxyHandler<VaporComponentInstance>,
] {
  if (comp.__propsHandlers) {
    return comp.__propsHandlers
  }
  const propsOptions = normalizePropsOptions(comp)[0]
  const emitsOptions = normalizeEmitsOptions(comp)
  const isProp = (
    propsOptions
      ? (key: string | symbol) =>
          isString(key) && hasOwn(propsOptions, camelize(key))
      : NO
  ) as (key: string | symbol) => key is string
  const isAttr = (
    propsOptions || emitsOptions
      ? (key: string | symbol) =>
          isString(key) &&
          key !== '$' &&
          !isReservedProp(key) &&
          !isProp(key) &&
          !isEmitListener(emitsOptions, key)
      : (key: string | symbol) => isString(key) && !isReservedProp(key)
  ) as (key: string | symbol) => key is string

  const getProp = (instance: VaporComponentInstance, key: string | symbol) => {
    // Keep direct props watchers shallow, as in VDOM.
    if (key === ReactiveFlags.IS_REACTIVE || key === ReactiveFlags.IS_SHALLOW)
      return true
    if (isProp(key)) {
      track(instance.propsValues, TrackOpTypes.GET, key)
      return instance.propsValues[key]
    }
  }

  const propsHandlers = propsOptions
    ? ({
        get: getProp,
        has: (_, key) => isProp(key),
        ownKeys: () => Object.keys(propsOptions),
        getOwnPropertyDescriptor(target, key) {
          if (isProp(key)) {
            return {
              configurable: true,
              enumerable: true,
              get: () => getProp(target, key),
            }
          }
        },
      } satisfies ProxyHandler<VaporComponentInstance>)
    : null

  if (__DEV__ && propsOptions) {
    Object.assign(propsHandlers!, {
      set: propsSetDevTrap,
      deleteProperty: propsDeleteDevTrap,
    })
  }

  const getAttr = (instance: VaporComponentInstance, key: string | symbol) => {
    if (isAttr(key)) {
      track(instance.propsValues, TrackOpTypes.GET, key)
      return instance.propsValues[key]
    }
  }
  const hasAttr = (instance: VaporComponentInstance, key: string | symbol) => {
    if (!isAttr(key)) return false
    track(instance.propsValues, TrackOpTypes.HAS, key)
    return hasOwn(instance.propsValues, key)
  }
  const attrsHandlers = {
    get: getAttr,
    has: hasAttr,
    ownKeys(target) {
      track(target.propsValues, TrackOpTypes.ITERATE, ITERATE_KEY)
      return Object.keys(target.propsValues).filter(isAttr)
    },
    getOwnPropertyDescriptor(target, key: string | symbol) {
      if (hasAttr(target, key)) {
        return {
          configurable: true,
          enumerable: true,
          get: () => getAttr(target, key),
        }
      }
    },
  } satisfies ProxyHandler<VaporComponentInstance>

  if (__DEV__) {
    Object.assign(attrsHandlers, {
      set: propsSetDevTrap,
      deleteProperty: propsDeleteDevTrap,
    })
  }

  return (comp.__propsHandlers = [propsHandlers, attrsHandlers])
}

export function getAttrFromRawProps(rawProps: RawProps, key: string): unknown {
  if (key === '$') return
  const dynamicSources = rawProps.$
  const isEvent = dynamicSources && isString(key) && isOn(key)
  // Class, style and event listeners merge across prop sources.
  const merged =
    key === 'class' || key === 'style' || isEvent ? ([] as any[]) : undefined
  if (dynamicSources) {
    let i = dynamicSources.length
    let source, isDynamic
    while (i--) {
      source = dynamicSources[i]
      isDynamic = isFunction(source)
      source = isDynamic
        ? resolveFunctionSource(source as () => Record<string, unknown>)
        : source
      if (source && hasOwn(source, key)) {
        const value = isDynamic ? source[key] : resolveSource(source[key])
        if (merged) {
          merged.push(value)
        } else {
          return value
        }
      }
    }
  }
  if (hasOwn(rawProps, key)) {
    const value = resolveSource(rawProps[key])
    if (merged) {
      merged.push(value)
    } else {
      return value
    }
  }
  if (merged && merged.length) {
    merged.reverse()
    return isEvent ? merged.reduce(mergeEventHandlers) : merged
  }
}

function mergeEventHandlers(existing: unknown, incoming: unknown): unknown {
  if (!existing) return incoming
  return incoming &&
    existing !== incoming &&
    !(isArray(existing) && existing.includes(incoming))
    ? ([] as unknown[]).concat(existing, incoming)
    : existing
}

export function hasAttrFromRawProps(rawProps: RawProps, key: string): boolean {
  if (key === '$') return false
  const dynamicSources = rawProps.$
  if (dynamicSources) {
    let i = dynamicSources.length
    while (i--) {
      const source = resolveSource(dynamicSources[i])
      if (source && hasOwn(source, key)) {
        return true
      }
    }
  }
  return hasOwn(rawProps, key)
}

export function getKeysFromRawProps(rawProps: RawProps): string[] {
  const keys: string[] = []
  for (const key in rawProps) {
    if (key !== '$') keys.push(key)
  }
  const dynamicSources = rawProps.$
  if (dynamicSources) {
    let i = dynamicSources.length
    let source
    while (i--) {
      source = isFunction(dynamicSources[i])
        ? resolveFunctionSource(
            dynamicSources[i] as () => Record<string, unknown>,
          )
        : dynamicSources[i]
      for (const key in source) {
        keys.push(key)
      }
    }
  }
  return Array.from(new Set(keys))
}

export function normalizePropsOptions(
  comp: VaporComponent,
): NormalizedPropsOptions {
  const cached = comp.__propsOptions
  if (cached) return cached

  const raw = comp.props
  if (!raw) return EMPTY_ARR as []

  const normalized: NormalizedPropsOptions[0] = {}
  const needCastKeys: NormalizedPropsOptions[1] = []
  baseNormalizePropsOptions(raw, normalized, needCastKeys)

  return (comp.__propsOptions = [normalized, needCastKeys])
}

function resolveDefault(
  factory: (props: Record<string, any>) => unknown,
  instance: VaporComponentInstance,
) {
  const prev = setCurrentInstance(instance)
  try {
    return factory.call(null, instance.props)
  } finally {
    restoreCurrentInstance(prev)
  }
}

export function hasFallthroughAttrs(
  comp: VaporComponent,
  rawProps: RawProps | null | undefined,
): boolean {
  if (rawProps) {
    // dynamic sources can produce attrs keys at any time
    if (rawProps.$) {
      return true
    }
    // otherwise fallthrough potential requires an undeclared static key —
    // static keys are fixed at creation, so an empty rawProps can never
    // produce attrs later
    const propsOptions = comp.props ? normalizePropsOptions(comp)[0]! : null
    for (const key in rawProps) {
      if (!propsOptions || !hasOwn(propsOptions, camelize(key))) {
        return true
      }
    }
  }
  return false
}

export function resolveDynamicProps(props: RawProps): Record<string, unknown> {
  const mergedRawProps: Record<string, any> = {}
  for (const key in props) {
    if (key !== '$') {
      mergedRawProps[key] = resolveSource(props[key])
    }
  }
  if (props.$) {
    for (const source of props.$) {
      const isDynamic = isFunction(source)
      const resolved = isDynamic ? resolveFunctionSource(source) : source
      for (const key in resolved) {
        const value = isDynamic ? resolved[key] : resolveSource(source[key])
        if (key === 'class' || key === 'style') {
          const existing = mergedRawProps[key]
          mergedRawProps[key] = isArray(existing)
            ? [...existing, value]
            : [existing, value]
        } else if (isOn(key)) {
          mergedRawProps[key] = mergeEventHandlers(mergedRawProps[key], value)
        } else {
          mergedRawProps[key] = value
        }
      }
    }
  }
  return mergedRawProps
}

// the static key bindings of a rawProps object: the own getters, plus the
// getters of a static group that follows a spread and so sits inside `$`
export function getStaticBindingKeys(props: RawProps): string[] {
  const keys: string[] = []
  for (const key in props) {
    if (key !== '$' && isFunction(props[key])) keys.push(key)
  }
  if (props.$) {
    for (const source of props.$) {
      if (!isFunction(source)) {
        for (const key in source) {
          if (isFunction(source[key])) keys.push(key)
        }
      }
    }
  }
  return keys
}

function propsSetDevTrap(_: any, key: string | symbol) {
  warn(
    `Attempt to mutate prop ${JSON.stringify(key)} failed. Props are readonly.`,
  )
  return true
}

function propsDeleteDevTrap(_: any, key: string | symbol) {
  warn(
    `Attempt to delete prop ${JSON.stringify(key)} failed. Props are readonly.`,
  )
  return true
}

export const rawPropsProxyHandlers: ProxyHandler<RawProps> = {
  get: getAttrFromRawProps,
  has: hasAttrFromRawProps,
  ownKeys: getKeysFromRawProps,
  getOwnPropertyDescriptor(target, key: string) {
    if (hasAttrFromRawProps(target, key)) {
      return {
        configurable: true,
        enumerable: true,
        get: () => getAttrFromRawProps(target, key),
      }
    }
  },
}

// Inputs belong to the child scope, but run in the parent's update order.
export function initProps(
  instance: VaporComponentInstance,
  once = false,
): void {
  const scope = instance.inputScope || instance.scope
  const previousEffect = instance.propsEffect
  if (previousEffect) previousEffect.stop()
  const parent = instance.parent
  const previous = setCurrentInstance(parent || instance, scope)
  try {
    const sources = instance.rawProps.$
    // VDOM already evaluated these inputs and delivers subsequent patches.
    if (once || (sources && sources[interopKey])) {
      const subscriber = setActiveSub()
      try {
        updateProps(instance, collectProps(instance.rawProps))
      } finally {
        setActiveSub(subscriber)
      }
      return
    }
    const input = new RenderEffect(() => {
      const context = setCurrentInstance(parent || instance, scope)
      let raw: Record<string, any>
      try {
        raw = collectProps(instance.rawProps)
      } finally {
        restoreCurrentInstance(context)
      }
      if (input.active) updateProps(instance, raw)
    }, true)
    instance.propsEffect = input
    if (!previousEffect) {
      input.run()
    } else {
      if (scope.flags & EffectFlags.PAUSED) input.pause()
      input.notify()
    }
  } catch (error) {
    // Initialization can fail before createComponent registers its teardown.
    if (instance.propsEffect) instance.propsEffect.stop()
    instance.scope.stop()
    if (instance.inputScope) instance.inputScope.stop()
    throw error
  } finally {
    restoreCurrentInstance(previous)
  }
}

export function collectProps(sources: RawProps): Record<string, any> {
  // Raw attrs may contain prototype-named keys such as __proto__.
  const raw: Record<string, any> = Object.create(null)
  const dynamicSources = sources.$ || EMPTY_ARR
  for (let i = -1; i < dynamicSources.length; i++) {
    const source = i < 0 ? sources : dynamicSources[i]
    const dynamic = isFunction(source)
    const resolved = dynamic ? source() : source
    for (const key in resolved) {
      if (i < 0 && key === '$') continue
      const value = dynamic ? resolved[key] : readSource(resolved[key])
      if (!dynamicSources.length) {
        raw[key] = value
      } else if (key === 'class') {
        if (raw.class !== value) raw.class = normalizeClass([raw.class, value])
      } else if (key === 'style') {
        raw.style = normalizeStyle([raw.style, value])
      } else if (isOn(key)) {
        const existing = raw[key]
        if (
          value &&
          existing !== value &&
          !(isArray(existing) && existing.includes(value))
        ) {
          raw[key] = existing ? ([] as any[]).concat(existing, value) : value
        } else if (value == null && existing == null && !isModelListener(key)) {
          raw[key] = value
        }
      } else if (key !== '') {
        raw[key] = value
      }
    }
  }
  if (raw.class && !isString(raw.class)) raw.class = normalizeClass(raw.class)
  if (raw.style && isObject(raw.style)) raw.style = normalizeStyle([raw.style])
  return raw
}

export function updateProps(
  instance: VaporComponentInstance,
  raw: Record<string, any>,
): void {
  const values = instance.propsValues
  const [options, castKeys] = normalizePropsOptions(instance.type)
  const emits = normalizeEmitsOptions(instance.type)
  const subscriber = setActiveSub()
  try {
    // Raw listeners become current before normalized keys notify watchers.
    instance.rawValues.value = stabilizeDynamicSourceValue(
      instance.rawValues.value,
      raw,
    )
    raw = instance.rawValues.value
    const vnode = isInteropEnabled && instance.interopVNode
    if (vnode && vnode.vi) vnode.props = raw
    const present: Record<string, true> = Object.create(null)
    const casts: Record<string, unknown> = Object.create(null)
    for (const key in raw) {
      if (isReservedProp(key)) continue
      const normalized = camelize(key)
      if (options && hasOwn(options, normalized)) {
        present[normalized] = true
        if (castKeys && castKeys.includes(normalized)) {
          casts[normalized] = raw[key]
        } else {
          setPropValue(values, normalized, raw[key])
        }
      } else if (!isEmitListener(emits, key)) {
        present[key] = true
        setPropValue(values, key, raw[key])
      }
    }
    if (castKeys) {
      for (const key of castKeys) {
        setPropValue(
          values,
          key,
          resolvePropValue(
            options!,
            key,
            casts[key],
            instance,
            resolveDefault,
            !hasOwn(casts, key),
          ),
        )
        present[key] = true
      }
    }
    for (const key in options) {
      if (!present[key]) {
        setPropValue(
          values,
          key,
          resolvePropValue(
            options,
            key,
            undefined,
            instance,
            resolveDefault,
            true,
          ),
        )
      }
      present[key] = true
    }
    for (const key in values) {
      if (!present[key]) {
        const oldValue = values[key]
        delete values[key]
        trigger(values, TriggerOpTypes.DELETE, key, undefined, oldValue)
      }
    }
    if (__DEV__ && options) {
      pushWarningContext(instance)
      try {
        validateProps(raw, instance.props, options)
      } finally {
        popWarningContext()
      }
    }
  } finally {
    setActiveSub(subscriber)
  }
}

function setPropValue(
  values: Record<string, any>,
  key: string,
  value: unknown,
) {
  const hadKey = hasOwn(values, key)
  const oldValue = values[key]
  values[key] = value
  if (!hadKey) {
    trigger(values, TriggerOpTypes.ADD, key, value)
  } else if (hasChanged(value, oldValue)) {
    trigger(values, TriggerOpTypes.SET, key, value, oldValue)
  }
}
