import {
  EMPTY_ARR,
  EMPTY_OBJ,
  NO,
  camelize,
  hasOwn,
  isArray,
  isFunction,
  isObject,
  isOn,
  isPlainObject,
  isReservedProp,
  isString,
  normalizeClass,
  normalizeStyle,
} from '@vue/shared'
import type { VaporComponent, VaporComponentInstance } from './component'
import {
  type GenericComponentInstance,
  type NormalizedPropsOptions,
  type VNode,
  baseNormalizePropsOptions,
  currentInstance,
  isEmitListener,
  popWarningContext,
  pushWarningContext,
  resolvePropValue,
  restoreCurrentInstance,
  setCurrentInstance,
  validateProps,
  warn,
} from '@vue/runtime-dom'
import {
  type ComputedRef,
  type ComputedRefImpl,
  type EffectScope,
  ReactiveFlags,
  type ShallowRef,
  computed,
  getCurrentScope,
  onScopeDispose,
  shallowRef,
} from '@vue/reactivity'
import { normalizeEmitsOptions } from './componentEmits'
import { renderEffect } from './renderEffect'
import { interopKey } from './vdomInteropState'

export type RawProps = Record<string, unknown> & {
  // generated by compiler for :[key]="x" or v-bind="x"
  $?: DynamicPropsSource[] & { [interopKey]?: boolean }
}

export type DynamicPropsSource =
  | (() => Record<string, unknown>)
  | Record<string, unknown>

export function resolveSource<T>(source: T | (() => T)): T {
  return isFunction(source) ? resolveFunctionSource(source as () => T) : source
}

type FunctionSource<T> = (() => T) & {
  _cache?: ComputedRef<T>
  // set by commitPropSources: the value the parent's queued commit published
  _committed?: ShallowRef<T>
}

export function resolveFunctionSource<T>(source: FunctionSource<T>): T {
  // use existing cache if available
  if (source._cache) {
    return source._cache.value
  }

  // source function is defined in the parent component, so it should be
  // executed in the parent's context. currentInstance is the child component
  // (the one accessing props/slots), so we use parent to get the component
  // where source was defined.
  const parent = currentInstance && currentInstance.parent
  if (parent) {
    // execute the source in the parent's context, but collect its cache in the
    // active consumer scope
    const prev = setCurrentInstance(parent, getCurrentScope())
    try {
      source._cache = computed(oldValue => {
        const committed = source._committed
        if (committed) return committed.value
        const prevInner = setCurrentInstance(parent)
        try {
          return stabilizeDynamicSourceValue(oldValue, source())
        } finally {
          restoreCurrentInstance(prevInner)
        }
      })
      onScopeDispose(() => (source._cache = undefined))
    } finally {
      restoreCurrentInstance(prev)
    }
    return source._cache.value
  }

  // no parent, no cache - read the committed value if there is one, else
  // call directly
  const committed = source._committed
  return committed ? committed.value : source()
}

/**
 * A prop getter is the parent's expression. Reading it outside the parent's
 * update order observes values the parent never committed: a `flush: 'sync'`
 * consumer runs inline, ahead of the queued structural update whose guard may
 * just have turned false (#15673), and a kept-alive component stays live while
 * its branch is deactivated (#15228). Publish the dynamic prop sources through
 * effects instead: they run as jobs after the parent's own effects, and
 * `scope` pauses or stops them.
 */
export function commitPropSources(
  rawProps: RawProps,
  parent: GenericComponentInstance,
  scope: EffectScope,
): void {
  const prev = setCurrentInstance(parent, scope)
  try {
    for (const key in rawProps) {
      if (key !== '$') commitSource(rawProps[key], parent)
    }
    const dynamicSources = rawProps.$
    // interop props are already committed by the vdom parent's patch
    if (dynamicSources && !dynamicSources[interopKey]) {
      for (let i = 0; i < dynamicSources.length; i++) {
        const source = dynamicSources[i]
        if (isFunction(source)) {
          commitSource(source, parent, true)
        } else {
          for (const key in source) commitSource(source[key], parent)
        }
      }
    }
  } finally {
    restoreCurrentInstance(prev)
  }
}

function commitSource(
  source: unknown,
  parent: GenericComponentInstance,
  // a v-bind source returns the props container itself, possibly a reactive
  // object; commit a copy of its top level so consumers depend on the commit
  // rather than on the container (nested values keep their identity)
  isContainer = false,
): void {
  // one committing owner per function identity: owners that overlap and pause
  // independently must clone the source first (see isolatePropSources)
  if (!isFunction(source) || (source as FunctionSource<unknown>)._committed) {
    return
  }
  const fn = source as FunctionSource<unknown>
  const committed = shallowRef<unknown>()
  let value: unknown
  renderEffect(() => {
    // the source is the parent's expression; evaluate it as the cache does
    const prevInner = setCurrentInstance(parent)
    try {
      let next = fn()
      if (isContainer && isObject(next)) {
        const copy: Record<string, unknown> = {}
        for (const key in next) copy[key] = next[key]
        next = copy
      }
      committed.value = value = stabilizeDynamicSourceValue(value, next)
    } finally {
      restoreCurrentInstance(prevInner)
    }
  }, true)
  // one property order for every source keeps the `_cache` load polymorphic
  if (!fn._cache) fn._cache = undefined
  fn._committed = committed
  onScopeDispose(() => (fn._committed = undefined))
  // a cache created before this point still depends on the raw source (and
  // on any computed the source read); re-track it onto the committed value
  // so a dirty check no longer descends into those
  const cache = fn._cache
  if (cache) (cache as unknown as ComputedRefImpl<unknown>).update()
}

/**
 * KeepAlive: cached siblings created from one `<component :is>` (or an async
 * wrapper's states) share the raw props object, but each needs its own commit
 * for its input scope to pause, so commit clones of the function sources.
 * Runs inside the input scope with the parent as the current instance.
 */
export function isolatePropSources(rawProps: RawProps): RawProps {
  let cloned = false
  const clone = (source: unknown): unknown => {
    if (!isFunction(source)) return source
    cloned = true
    return () => source()
  }
  const isolated: RawProps = {}
  for (const key in rawProps) {
    if (key !== '$') isolated[key] = clone(rawProps[key])
  }
  const dynamicSources = rawProps.$
  if (dynamicSources) {
    const clones: DynamicPropsSource[] = (isolated.$ = [])
    for (let i = 0; i < dynamicSources.length; i++) {
      const source = dynamicSources[i]
      if (isFunction(source)) {
        clones[i] = clone(source) as () => Record<string, unknown>
      } else {
        const copy: Record<string, unknown> = {}
        for (const key in source) copy[key] = clone(source[key])
        clones[i] = copy
      }
    }
  }
  if (!cloned) return rawProps
  commitPropSources(isolated, currentInstance!, getCurrentScope()!)
  return isolated
}

export function snapshotRawProps(rawProps: RawProps): RawProps {
  // Freeze the parent-provided raw source, not the child props proxy. This
  // keeps prop defaults lazy while preserving v-once input semantics.
  // Sources are read directly: the caller is the instance that defined them,
  // and a one-time read has no use for the computed `resolveFunctionSource`
  // would allocate. Values are stored plain; only a function value needs a
  // getter so readers do not invoke it.
  const snapshot: RawProps = Object.create(null)
  for (const key in rawProps) {
    if (key !== '$') {
      snapshot[key] = freezeValue(key, readSource(rawProps[key]))
    }
  }

  const dynamicSources = rawProps.$
  if (dynamicSources) {
    const snapshotSources: DynamicPropsSource[] & {
      [interopKey]?: boolean
    } = []
    for (let i = 0; i < dynamicSources.length; i++) {
      const source = dynamicSources[i]
      const isDynamic = isFunction(source)
      const resolved = readSource(source) || EMPTY_OBJ
      // Object sources are read without a per-source computed, so a resolved
      // function source is stored in that shape.
      const value: Record<string, unknown> = Object.create(null)
      for (const key in resolved) {
        value[key] = freezeValue(
          key,
          isDynamic ? resolved[key] : readSource(resolved[key]),
        )
      }
      snapshotSources[i] = value
    }
    const symbols = Object.getOwnPropertySymbols(dynamicSources)
    for (let i = 0; i < symbols.length; i++) {
      ;(snapshotSources as any)[symbols[i]] = (dynamicSources as any)[
        symbols[i]
      ]
    }
    snapshot.$ = snapshotSources
  }

  return snapshot
}

function readSource<T>(source: T | (() => T)): T {
  return isFunction(source) ? (source as () => T)() : source
}

function freezeValue(key: string, value: unknown): unknown {
  if (key === 'class' && value && !isString(value)) return normalizeClass(value)
  // wrapped so a lone (possibly reactive) style object is copied too
  if (key === 'style' && isObject(value)) return normalizeStyle([value])
  return isFunction(value) ? () => value : value
}

function stabilizeDynamicSourceValue<T>(oldValue: T | undefined, value: T): T {
  if (!isPlainObject(oldValue) || !isPlainObject(value)) {
    return value
  }

  // Dynamic sources often allocate a fresh object even when the resolved
  // props/attrs are unchanged. Keep the previous identity in that case so
  // computed consumers do not trigger child updates for equivalent values.
  const oldKeys = Object.keys(oldValue)
  const newKeys = Object.keys(value)
  if (oldKeys.length !== newKeys.length) {
    return value
  }

  for (let i = 0; i < newKeys.length; i++) {
    const key = newKeys[i]
    if (
      !hasOwn(oldValue, key) ||
      !Object.is((oldValue as any)[key], (value as any)[key])
    ) {
      return value
    }
  }

  return oldValue
}

export function getPropsProxyHandlers(
  comp: VaporComponent,
): [
  ProxyHandler<VaporComponentInstance> | null,
  ProxyHandler<VaporComponentInstance>,
] {
  if (comp.__propsHandlers) {
    return comp.__propsHandlers
  }
  const propsOptions = normalizePropsOptions(comp)[0]
  const emitsOptions = normalizeEmitsOptions(comp)
  const isProp = (
    propsOptions
      ? (key: string | symbol) =>
          isString(key) && hasOwn(propsOptions, camelize(key))
      : NO
  ) as (key: string | symbol) => key is string
  const isAttr = (
    propsOptions || emitsOptions
      ? (key: string | symbol) =>
          isString(key) &&
          key !== '$' &&
          !isReservedProp(key) &&
          !isProp(key) &&
          !isEmitListener(emitsOptions, key)
      : (key: string | symbol) => isString(key) && !isReservedProp(key)
  ) as (key: string | symbol) => key is string

  // vdom normalizes class and style on the vnode, so prop resolution already
  // receives normalized values. Match that order here.
  const normalizeRawProp = (key: string, value: unknown) => {
    if (!value) return value
    if (key === 'class' && !isString(value)) return normalizeClass(value)
    if (key === 'style' && isObject(value)) return normalizeStyle(value)
    return value
  }

  const getProp = (instance: VaporComponentInstance, key: string | symbol) => {
    // this enables direct watching of props and prevents `Invalid watch source` DEV warnings.
    // props are shallow reactive in vdom, so watching them should not traverse deeply.
    if (key === ReactiveFlags.IS_REACTIVE || key === ReactiveFlags.IS_SHALLOW)
      return true

    if (!isProp(key)) return
    const rawProps = instance.rawProps
    const dynamicSources = rawProps.$
    if (dynamicSources && isOn(key)) {
      const handlers: Record<string, unknown> = {}
      let matchedKey: string | undefined
      // Match mergeProps: merge exact raw keys in source order before
      // resolving camelized aliases in their first occurrence order.
      for (let i = -1; i < dynamicSources.length; i++) {
        const source = i < 0 ? rawProps : dynamicSources[i]
        const isDynamic = isFunction(source)
        const resolved = isDynamic ? resolveFunctionSource(source) : source
        for (const rawKey in resolved) {
          if (camelize(rawKey) === key) {
            if (!hasOwn(handlers, rawKey)) matchedKey = rawKey
            const value = isDynamic
              ? resolved[rawKey]
              : resolveSource(resolved[rawKey])
            handlers[rawKey] = mergeEventHandlers(handlers[rawKey], value)
          }
        }
      }
      return resolvePropValue(
        propsOptions!,
        key,
        matchedKey === undefined ? undefined : handlers[matchedKey],
        instance,
        resolveDefault,
        matchedKey === undefined,
      )
    }
    const merged =
      dynamicSources && (key === 'class' || key === 'style')
        ? ([] as unknown[])
        : undefined
    if (dynamicSources) {
      let i = dynamicSources.length
      let source, isDynamic, rawKey
      while (i--) {
        source = dynamicSources[i]
        isDynamic = isFunction(source)
        source = isDynamic
          ? (resolveFunctionSource(
              source as () => Record<string, unknown>,
            ) as any)
          : source
        for (rawKey in source) {
          if (camelize(rawKey) === key) {
            const value = isDynamic
              ? source[rawKey]
              : resolveSource(source[rawKey])
            if (merged) {
              merged.push(value)
            } else {
              return resolvePropValue(
                propsOptions!,
                key,
                normalizeRawProp(key, value),
                instance,
                resolveDefault,
              )
            }
          }
        }
      }
    }
    for (const rawKey in rawProps) {
      if (camelize(rawKey) === key) {
        const value = resolveSource(rawProps[rawKey])
        if (merged) {
          merged.push(value)
        } else {
          return resolvePropValue(
            propsOptions!,
            key,
            normalizeRawProp(key, value),
            instance,
            resolveDefault,
          )
        }
      }
    }
    const hasMerged = !!(merged && merged.length)
    let value
    if (hasMerged) {
      if (merged.length === 1) {
        value = merged[0]
      } else if (key === 'class') {
        // Match mergeProps, including leaving all-undefined classes undefined.
        for (let i = merged.length - 1; i >= 0; i--) {
          if (value !== merged[i]) {
            value = normalizeClass([value, merged[i]])
          }
        }
      } else {
        value = merged.reverse()
      }
    }
    return resolvePropValue(
      propsOptions!,
      key,
      normalizeRawProp(key, value),
      instance,
      resolveDefault,
      !hasMerged,
    )
  }

  const propsHandlers = propsOptions
    ? ({
        get: getProp,
        has: (_, key) => isProp(key),
        ownKeys: () => Object.keys(propsOptions),
        getOwnPropertyDescriptor(target, key) {
          if (isProp(key)) {
            return {
              configurable: true,
              enumerable: true,
              get: () => getProp(target, key),
            }
          }
        },
      } satisfies ProxyHandler<VaporComponentInstance>)
    : null

  if (__DEV__ && propsOptions) {
    Object.assign(propsHandlers!, {
      set: propsSetDevTrap,
      deleteProperty: propsDeleteDevTrap,
    })
  }

  const getAttr = (target: RawProps, key: string | symbol) => {
    if (
      isString(key) &&
      !isReservedProp(key) &&
      !isProp(key) &&
      !isEmitListener(emitsOptions, key)
    ) {
      return getAttrFromRawProps(target, key)
    }
  }

  const hasAttr = (target: RawProps, key: string | symbol) => {
    if (isAttr(key)) {
      return hasAttrFromRawProps(target, key)
    } else {
      return false
    }
  }

  const getAttrKeys = (target: VaporComponentInstance) =>
    getKeysFromRawProps(target.rawProps).filter(isAttr)
  const attrsHandlers = {
    get: (target, key: string | symbol) => getAttr(target.rawProps, key),
    has: (target, key: string | symbol) => hasAttr(target.rawProps, key),
    ownKeys: getAttrKeys,
    getOwnPropertyDescriptor(target, key: string | symbol) {
      if (isString(key) && hasAttr(target.rawProps, key)) {
        return {
          configurable: true,
          enumerable: true,
          get: () => getAttr(target.rawProps, key),
        }
      }
    },
  } satisfies ProxyHandler<VaporComponentInstance>

  if (__DEV__) {
    Object.assign(attrsHandlers, {
      set: propsSetDevTrap,
      deleteProperty: propsDeleteDevTrap,
    })
  }

  return (comp.__propsHandlers = [propsHandlers, attrsHandlers])
}

export function getAttrFromRawProps(rawProps: RawProps, key: string): unknown {
  if (key === '$') return
  const dynamicSources = rawProps.$
  const isEvent = dynamicSources && isString(key) && isOn(key)
  // Class, style and event listeners merge across prop sources.
  const merged =
    key === 'class' || key === 'style' || isEvent ? ([] as any[]) : undefined
  if (dynamicSources) {
    let i = dynamicSources.length
    let source, isDynamic
    while (i--) {
      source = dynamicSources[i]
      isDynamic = isFunction(source)
      source = isDynamic
        ? resolveFunctionSource(source as () => Record<string, unknown>)
        : source
      if (source && hasOwn(source, key)) {
        const value = isDynamic ? source[key] : resolveSource(source[key])
        if (merged) {
          merged.push(value)
        } else {
          return value
        }
      }
    }
  }
  if (hasOwn(rawProps, key)) {
    const value = resolveSource(rawProps[key])
    if (merged) {
      merged.push(value)
    } else {
      return value
    }
  }
  if (merged && merged.length) {
    merged.reverse()
    return isEvent ? merged.reduce(mergeEventHandlers) : merged
  }
}

function mergeEventHandlers(existing: unknown, incoming: unknown): unknown {
  if (!existing) return incoming
  return incoming &&
    existing !== incoming &&
    !(isArray(existing) && existing.includes(incoming))
    ? ([] as unknown[]).concat(existing, incoming)
    : existing
}

export function hasAttrFromRawProps(rawProps: RawProps, key: string): boolean {
  if (key === '$') return false
  const dynamicSources = rawProps.$
  if (dynamicSources) {
    let i = dynamicSources.length
    while (i--) {
      const source = resolveSource(dynamicSources[i])
      if (source && hasOwn(source, key)) {
        return true
      }
    }
  }
  return hasOwn(rawProps, key)
}

export function getKeysFromRawProps(rawProps: RawProps): string[] {
  const keys: string[] = []
  for (const key in rawProps) {
    if (key !== '$') keys.push(key)
  }
  const dynamicSources = rawProps.$
  if (dynamicSources) {
    let i = dynamicSources.length
    let source
    while (i--) {
      source = isFunction(dynamicSources[i])
        ? resolveFunctionSource(
            dynamicSources[i] as () => Record<string, unknown>,
          )
        : dynamicSources[i]
      for (const key in source) {
        keys.push(key)
      }
    }
  }
  return Array.from(new Set(keys))
}

export function normalizePropsOptions(
  comp: VaporComponent,
): NormalizedPropsOptions {
  const cached = comp.__propsOptions
  if (cached) return cached

  const raw = comp.props
  if (!raw) return EMPTY_ARR as []

  const normalized: NormalizedPropsOptions[0] = {}
  const needCastKeys: NormalizedPropsOptions[1] = []
  baseNormalizePropsOptions(raw, normalized, needCastKeys)

  return (comp.__propsOptions = [normalized, needCastKeys])
}

function resolveDefault(
  factory: (props: Record<string, any>) => unknown,
  instance: VaporComponentInstance,
) {
  const prev = setCurrentInstance(instance)
  const res = factory.call(null, instance.props)
  restoreCurrentInstance(prev)
  return res
}

export function hasFallthroughAttrs(
  comp: VaporComponent,
  rawProps: RawProps | null | undefined,
): boolean {
  if (rawProps) {
    // dynamic sources can produce attrs keys at any time
    if (rawProps.$) {
      return true
    }
    // otherwise fallthrough potential requires an undeclared static key —
    // static keys are fixed at creation, so an empty rawProps can never
    // produce attrs later
    const propsOptions = comp.props ? normalizePropsOptions(comp)[0]! : null
    for (const key in rawProps) {
      if (!propsOptions || !hasOwn(propsOptions, camelize(key))) {
        return true
      }
    }
  }
  return false
}

/**
 * dev only
 */
export function setupPropsValidation(
  instance: VaporComponentInstance,
  warningContext: GenericComponentInstance | VNode = instance,
): void {
  const rawProps = instance.rawProps
  if (!rawProps) return
  renderEffect(() => {
    pushWarningContext(warningContext)
    validateProps(
      resolveDynamicProps(rawProps),
      instance.props,
      normalizePropsOptions(instance.type)[0]!,
    )
    popWarningContext()
  }, true /* noLifecycle */)
}

export function resolveDynamicProps(props: RawProps): Record<string, unknown> {
  const mergedRawProps: Record<string, any> = {}
  for (const key in props) {
    if (key !== '$') {
      mergedRawProps[key] = resolveSource(props[key])
    }
  }
  if (props.$) {
    for (const source of props.$) {
      const isDynamic = isFunction(source)
      const resolved = isDynamic ? resolveFunctionSource(source) : source
      for (const key in resolved) {
        const value = isDynamic ? resolved[key] : resolveSource(source[key])
        if (key === 'class' || key === 'style') {
          const existing = mergedRawProps[key]
          mergedRawProps[key] = isArray(existing)
            ? [...existing, value]
            : [existing, value]
        } else if (isOn(key)) {
          mergedRawProps[key] = mergeEventHandlers(mergedRawProps[key], value)
        } else {
          mergedRawProps[key] = value
        }
      }
    }
  }
  return mergedRawProps
}

// the static key bindings of a rawProps object: the own getters, plus the
// getters of a static group that follows a spread and so sits inside `$`
export function getStaticBindingKeys(props: RawProps): string[] {
  const keys: string[] = []
  for (const key in props) {
    if (key !== '$' && isFunction(props[key])) keys.push(key)
  }
  if (props.$) {
    for (const source of props.$) {
      if (!isFunction(source)) {
        for (const key in source) {
          if (isFunction(source[key])) keys.push(key)
        }
      }
    }
  }
  return keys
}

function propsSetDevTrap(_: any, key: string | symbol) {
  warn(
    `Attempt to mutate prop ${JSON.stringify(key)} failed. Props are readonly.`,
  )
  return true
}

function propsDeleteDevTrap(_: any, key: string | symbol) {
  warn(
    `Attempt to delete prop ${JSON.stringify(key)} failed. Props are readonly.`,
  )
  return true
}

export const rawPropsProxyHandlers: ProxyHandler<RawProps> = {
  get: getAttrFromRawProps,
  has: hasAttrFromRawProps,
  ownKeys: getKeysFromRawProps,
  getOwnPropertyDescriptor(target, key: string) {
    if (hasAttrFromRawProps(target, key)) {
      return {
        configurable: true,
        enumerable: true,
        get: () => getAttrFromRawProps(target, key),
      }
    }
  },
}
