import {
  EMPTY_ARR,
  EMPTY_OBJ,
  NO,
  camelize,
  hasChanged,
  hasOwn,
  isArray,
  isFunction,
  isModelListener,
  isObject,
  isOn,
  isPlainObject,
  isReservedProp,
  isString,
  normalizeClass,
  normalizeStyle,
} from '@vue/shared'
import type { VaporComponent, VaporComponentInstance } from './component'
import type { SlotSourceCell } from './componentSlots'
import {
  type NormalizedPropsOptions,
  baseNormalizePropsOptions,
  currentInstance,
  isEmitListener,
  popWarningContext,
  pushWarningContext,
  resolvePropValue,
  restoreCurrentInstance,
  setCurrentInstance,
  validateProps,
  warn,
} from '@vue/runtime-dom'
import {
  Dep,
  EffectFlags,
  ReactiveFlags,
  activeSub,
  computed,
  endBatch,
  getCurrentScope,
  onScopeDispose,
  setActiveSub,
  startBatch,
  trackDep,
  triggerDep,
} from '@vue/reactivity'
import { normalizeEmitsOptions } from './componentEmits'
import { RenderEffect } from './renderEffect'
import { interopKey, isInteropEnabled } from './vdomInteropState'

export type RawProps = Record<string, unknown> & {
  // generated by compiler for :[key]="x" or v-bind="x"
  $?: DynamicPropsSource[] & { [interopKey]?: boolean }
}

export type DynamicPropsSource =
  | (() => Record<string, unknown>)
  | Record<string, unknown>

export function resolveSource<T>(source: T | (() => T)): T {
  return isFunction(source) ? resolveFunctionSource(source as () => T) : source
}

export type FunctionSource<T> = (() => T) & {
  _cache?: { readonly value: T }
}

export function resolveFunctionSource<T>(source: FunctionSource<T>): T {
  // use existing cache if available
  if (source._cache) {
    return source._cache.value
  }

  // source function is defined in the parent component, so it should be
  // executed in the parent's context. currentInstance is the child component
  // (the one accessing props/slots), so we use parent to get the component
  // where source was defined.
  const parent = currentInstance && currentInstance.parent
  if (parent) {
    // execute the source in the parent's context, but collect its cache in the
    // active consumer scope
    const prev = setCurrentInstance(parent, getCurrentScope())
    try {
      source._cache = computed(oldValue => {
        const prevInner = setCurrentInstance(parent)
        try {
          return stabilizeDynamicSourceValue(oldValue, source())
        } finally {
          restoreCurrentInstance(prevInner)
        }
      })
      onScopeDispose(() => (source._cache = undefined))
    } finally {
      restoreCurrentInstance(prev)
    }
    return source._cache.value
  }

  return source()
}

export function snapshotRawProps(rawProps: RawProps): RawProps {
  // Freeze the parent-provided raw source, not the child props proxy. This
  // keeps prop defaults lazy while preserving v-once input semantics.
  // Sources are read directly: the caller is the instance that defined them,
  // and a one-time read has no use for the computed `resolveFunctionSource`
  // would allocate. Values are stored plain; only a function value needs a
  // getter so readers do not invoke it.
  const snapshot: RawProps = Object.create(null)
  for (const key in rawProps) {
    if (key !== '$') {
      snapshot[key] = freezeValue(key, readSource(rawProps[key]))
    }
  }

  const dynamicSources = rawProps.$
  if (dynamicSources) {
    const snapshotSources: DynamicPropsSource[] & {
      [interopKey]?: boolean
    } = []
    for (let i = 0; i < dynamicSources.length; i++) {
      const source = dynamicSources[i]
      const isDynamic = isFunction(source)
      const resolved = readSource(source) || EMPTY_OBJ
      // Object sources are read without a per-source computed, so a resolved
      // function source is stored in that shape.
      const value: Record<string, unknown> = Object.create(null)
      for (const key in resolved) {
        value[key] = freezeValue(
          key,
          isDynamic ? resolved[key] : readSource(resolved[key]),
        )
      }
      snapshotSources[i] = value
    }
    const symbols = Object.getOwnPropertySymbols(dynamicSources)
    for (let i = 0; i < symbols.length; i++) {
      ;(snapshotSources as any)[symbols[i]] = (dynamicSources as any)[
        symbols[i]
      ]
    }
    snapshot.$ = snapshotSources
  }

  return snapshot
}

function readSource<T>(source: T | (() => T)): T {
  return isFunction(source) ? (source as () => T)() : source
}

function freezeValue(key: string, value: unknown): unknown {
  value = normalizePropValue(key, value)
  return isFunction(value) ? () => value : value
}

// class and style are delivered normalized, as mergeProps would
function normalizePropValue(
  key: string,
  value: unknown,
  prevValue?: unknown,
): unknown {
  if (key === 'class') {
    return value && !isString(value) ? normalizeClass(value) : value
  }
  // wrapped so a lone (possibly reactive) style object is copied too; the
  // copy is a new object, so an equal style is the one already delivered
  return key === 'style' && isObject(value)
    ? stabilizeDynamicSourceValue(prevValue, normalizeStyle([value]))
    : value
}

export function stabilizeDynamicSourceValue<T>(
  oldValue: T | undefined,
  value: T,
): T {
  if (!isPlainObject(oldValue) || !isPlainObject(value)) {
    return value
  }

  // Dynamic sources often allocate a fresh object even when the resolved
  // props/attrs are unchanged. Keep the previous identity in that case so
  // computed consumers do not trigger child updates for equivalent values.
  const oldKeys = Object.keys(oldValue)
  const newKeys = Object.keys(value)
  if (oldKeys.length !== newKeys.length) {
    return value
  }

  for (let i = 0; i < newKeys.length; i++) {
    const key = newKeys[i]
    if (
      !hasOwn(oldValue, key) ||
      !Object.is((oldValue as any)[key], (value as any)[key])
    ) {
      return value
    }
  }

  return oldValue
}

export function getPropsProxyHandlers(
  comp: VaporComponent,
): [
  ProxyHandler<VaporComponentInstance> | null,
  ProxyHandler<VaporComponentInstance>,
] {
  if (comp.__propsHandlers) {
    return comp.__propsHandlers
  }
  const propsOptions = normalizePropsOptions(comp)[0]
  const emitsOptions = normalizeEmitsOptions(comp)
  const isProp = (
    propsOptions
      ? (key: string | symbol) =>
          isString(key) && hasOwn(propsOptions, camelize(key))
      : NO
  ) as (key: string | symbol) => key is string
  const isAttr = (
    propsOptions || emitsOptions
      ? (key: string | symbol) =>
          isString(key) &&
          key !== '$' &&
          !isReservedProp(key) &&
          !isProp(key) &&
          !isEmitListener(emitsOptions, key)
      : (key: string | symbol) => isString(key) && !isReservedProp(key)
  ) as (key: string | symbol) => key is string

  const getProp = (instance: VaporComponentInstance, key: string | symbol) => {
    // Keep direct props watchers shallow, as in VDOM.
    if (key === ReactiveFlags.IS_REACTIVE || key === ReactiveFlags.IS_SHALLOW)
      return true
    if (isProp(key)) {
      trackPropsValue(instance, key)
      return instance.propsValues[key]
    }
  }

  const propsHandlers = propsOptions
    ? ({
        get: getProp,
        has: (_, key) => isProp(key),
        ownKeys: () => Object.keys(propsOptions),
        getOwnPropertyDescriptor(target, key) {
          if (isProp(key)) {
            return {
              configurable: true,
              enumerable: true,
              get: () => getProp(target, key),
            }
          }
        },
      } satisfies ProxyHandler<VaporComponentInstance>)
    : null

  if (__DEV__ && propsOptions) {
    Object.assign(propsHandlers!, {
      set: propsSetDevTrap,
      deleteProperty: propsDeleteDevTrap,
    })
  }

  const getAttr = (instance: VaporComponentInstance, key: string | symbol) => {
    if (isAttr(key)) {
      trackPropsValue(instance, key)
      return instance.propsValues[key]
    }
  }
  const hasAttr = (instance: VaporComponentInstance, key: string | symbol) => {
    if (!isAttr(key)) return false
    trackPropsValue(instance, key)
    return hasOwn(instance.propsValues, key)
  }
  const attrsHandlers = {
    get: getAttr,
    has: hasAttr,
    ownKeys(target) {
      trackPropsValue(target, ATTR_KEYS)
      return Object.keys(target.propsValues).filter(isAttr)
    },
    getOwnPropertyDescriptor(target, key: string | symbol) {
      if (hasAttr(target, key)) {
        return {
          configurable: true,
          enumerable: true,
          get: () => getAttr(target, key),
        }
      }
    },
  } satisfies ProxyHandler<VaporComponentInstance>

  if (__DEV__) {
    Object.assign(attrsHandlers, {
      set: propsSetDevTrap,
      deleteProperty: propsDeleteDevTrap,
    })
  }

  return (comp.__propsHandlers = [propsHandlers, attrsHandlers])
}

export function getAttrFromRawProps(rawProps: RawProps, key: string): unknown {
  if (key === '$') return
  const dynamicSources = rawProps.$
  const isEvent = dynamicSources && isString(key) && isOn(key)
  // Class, style and event listeners merge across prop sources.
  const merged =
    key === 'class' || key === 'style' || isEvent ? ([] as any[]) : undefined
  if (dynamicSources) {
    let i = dynamicSources.length
    let source, isDynamic
    while (i--) {
      source = dynamicSources[i]
      isDynamic = isFunction(source)
      source = isDynamic
        ? resolveFunctionSource(source as () => Record<string, unknown>)
        : source
      if (source && hasOwn(source, key)) {
        const value = isDynamic ? source[key] : resolveSource(source[key])
        if (merged) {
          merged.push(value)
        } else {
          return value
        }
      }
    }
  }
  if (hasOwn(rawProps, key)) {
    const value = resolveSource(rawProps[key])
    if (merged) {
      merged.push(value)
    } else {
      return value
    }
  }
  if (merged && merged.length) {
    merged.reverse()
    return isEvent ? merged.reduce(mergeEventHandlers) : merged
  }
}

function mergeEventHandlers(existing: unknown, incoming: unknown): unknown {
  if (!existing) return incoming
  return incoming &&
    existing !== incoming &&
    !(isArray(existing) && existing.includes(incoming))
    ? ([] as unknown[]).concat(existing, incoming)
    : existing
}

export function hasAttrFromRawProps(rawProps: RawProps, key: string): boolean {
  if (key === '$') return false
  const dynamicSources = rawProps.$
  if (dynamicSources) {
    let i = dynamicSources.length
    while (i--) {
      const source = resolveSource(dynamicSources[i])
      if (source && hasOwn(source, key)) {
        return true
      }
    }
  }
  return hasOwn(rawProps, key)
}

export function getKeysFromRawProps(rawProps: RawProps): string[] {
  const keys: string[] = []
  for (const key in rawProps) {
    if (key !== '$') keys.push(key)
  }
  const dynamicSources = rawProps.$
  if (dynamicSources) {
    let i = dynamicSources.length
    let source
    while (i--) {
      source = isFunction(dynamicSources[i])
        ? resolveFunctionSource(
            dynamicSources[i] as () => Record<string, unknown>,
          )
        : dynamicSources[i]
      for (const key in source) {
        keys.push(key)
      }
    }
  }
  return Array.from(new Set(keys))
}

export function normalizePropsOptions(
  comp: VaporComponent,
): NormalizedPropsOptions {
  const cached = comp.__propsOptions
  if (cached) return cached

  const raw = comp.props
  if (!raw) return EMPTY_ARR as []

  const normalized: NormalizedPropsOptions[0] = {}
  const needCastKeys: NormalizedPropsOptions[1] = []
  baseNormalizePropsOptions(raw, normalized, needCastKeys)

  return (comp.__propsOptions = [normalized, needCastKeys])
}

function resolveDefault(
  factory: (props: Record<string, any>) => unknown,
  instance: VaporComponentInstance,
) {
  const prev = setCurrentInstance(instance)
  try {
    return factory.call(null, instance.props)
  } finally {
    restoreCurrentInstance(prev)
  }
}

export function hasFallthroughAttrs(
  comp: VaporComponent,
  rawProps: RawProps | null | undefined,
): boolean {
  if (rawProps) {
    // dynamic sources can produce attrs keys at any time
    if (rawProps.$) {
      return true
    }
    // otherwise fallthrough potential requires an undeclared static key —
    // static keys are fixed at creation, so an empty rawProps can never
    // produce attrs later
    const propsOptions = comp.props ? normalizePropsOptions(comp)[0]! : null
    for (const key in rawProps) {
      if (!propsOptions || !hasOwn(propsOptions, camelize(key))) {
        return true
      }
    }
  }
  return false
}

export function resolveDynamicProps(props: RawProps): Record<string, unknown> {
  const mergedRawProps: Record<string, any> = {}
  for (const key in props) {
    if (key !== '$') {
      mergedRawProps[key] = resolveSource(props[key])
    }
  }
  if (props.$) {
    for (const source of props.$) {
      const isDynamic = isFunction(source)
      const resolved = isDynamic ? resolveFunctionSource(source) : source
      for (const key in resolved) {
        const value = isDynamic ? resolved[key] : resolveSource(source[key])
        if (key === 'class' || key === 'style') {
          const existing = mergedRawProps[key]
          mergedRawProps[key] = isArray(existing)
            ? [...existing, value]
            : [existing, value]
        } else if (isOn(key)) {
          mergedRawProps[key] = mergeEventHandlers(mergedRawProps[key], value)
        } else {
          mergedRawProps[key] = value
        }
      }
    }
  }
  return mergedRawProps
}

// the static key bindings of a rawProps object: the own getters, plus the
// getters of a static group that follows a spread and so sits inside `$`
export function getStaticBindingKeys(props: RawProps): string[] {
  const keys: string[] = []
  for (const key in props) {
    if (key !== '$' && isFunction(props[key])) keys.push(key)
  }
  if (props.$) {
    for (const source of props.$) {
      if (!isFunction(source)) {
        for (const key in source) {
          if (isFunction(source[key])) keys.push(key)
        }
      }
    }
  }
  return keys
}

function propsSetDevTrap(_: any, key: string | symbol) {
  warn(
    `Attempt to mutate prop ${JSON.stringify(key)} failed. Props are readonly.`,
  )
  return true
}

function propsDeleteDevTrap(_: any, key: string | symbol) {
  warn(
    `Attempt to delete prop ${JSON.stringify(key)} failed. Props are readonly.`,
  )
  return true
}

export const rawPropsProxyHandlers: ProxyHandler<RawProps> = {
  get: getAttrFromRawProps,
  has: hasAttrFromRawProps,
  ownKeys: getKeysFromRawProps,
  getOwnPropertyDescriptor(target, key: string) {
    if (hasAttrFromRawProps(target, key)) {
      return {
        configurable: true,
        enumerable: true,
        get: () => getAttrFromRawProps(target, key),
      }
    }
  },
}

const RAW_VALUES_KEY: unique symbol = Symbol(__DEV__ ? 'Raw values' : '')
const ATTR_KEYS: unique symbol = Symbol(__DEV__ ? 'Attr keys' : '')

// `rawValues` before the first delivery
export const INITIAL_RAW_VALUES: Record<string, any> = {}

// One dep per key, on the instance rather than in `targetMap`, created for
// a subscriber only.
function trackPropsValue(
  instance: VaporComponentInstance,
  key: string | symbol,
): void {
  if (!instance.hasDynamicProps || activeSub === undefined) return
  const deps = instance.propsDeps || (instance.propsDeps = Object.create(null))
  trackDep(deps[key] || (deps[key] = new Dep()))
}

function triggerPropsValue(
  instance: VaporComponentInstance,
  key: string | symbol,
): void {
  const deps = instance.propsDeps
  if (deps) {
    const dep = deps[key]
    if (dep) triggerDep(dep)
  }
}

// Subscribes to every delivered input. `rawValues` itself is read untracked:
// emit and rawKeys must not subscribe their caller, as a vnode would not.
export function trackRawValues(
  instance: VaporComponentInstance,
): Record<string, any> {
  trackPropsValue(instance, RAW_VALUES_KEY)
  return instance.rawValues
}

// Inputs belong to the child scope, but run in the parent's update order.
export function initProps(
  instance: VaporComponentInstance,
  once = false,
): void {
  const scope = instance.inputScope || instance.scope
  const prevEffect = instance.propsEffect
  if (prevEffect) prevEffect.stop()
  const parent = instance.parent || instance
  const rawProps = instance.rawProps
  const cells = instance.slotSources
  const prev = setCurrentInstance(parent, scope)
  try {
    const dynamicSources = rawProps.$
    // VDOM already evaluated these inputs and delivers subsequent patches.
    const isInterop =
      isInteropEnabled && !!(dynamicSources && dynamicSources[interopKey])
    // a cache hit can rebind a kept-alive instance to other inputs
    const canRebind = !!instance.inputScope
    const hasGetters = hasDynamicPropsSource(rawProps)
    if (once || (!cells && (isInterop || (!canRebind && !hasGetters)))) {
      instance.hasDynamicProps = !once && isInterop
      const prevSub = setActiveSub()
      let rawValues: Record<string, any>
      try {
        rawValues = collectProps(rawProps)
        if (cells) collectSlotSources(cells)
      } finally {
        setActiveSub(prevSub)
      }
      deliverInputs(instance, rawValues, undefined, cells)
      return
    }
    instance.hasDynamicProps = canRebind || hasGetters
    // without dynamic sources the keys are static: after the first delivery
    // only the getters can change
    const hasStaticKeys = !dynamicSources
    let hasDelivered = false
    const effect = new RenderEffect(() => {
      const prevRawValues = instance.rawValues
      const prevInner = setCurrentInstance(parent, scope)
      let rawValues: Record<string, any> | undefined
      let propsToUpdate: unknown[] | undefined
      try {
        if (!hasDelivered || instance.hasDynamicProps) {
          if (hasDelivered && hasStaticKeys) {
            propsToUpdate = collectPropsToUpdate(rawProps, prevRawValues)
          } else {
            rawValues = collectProps(rawProps, prevRawValues.style)
            if (
              hasDelivered &&
              stabilizeDynamicSourceValue(prevRawValues, rawValues) ===
                prevRawValues
            ) {
              rawValues = undefined
            }
          }
        }
        if (cells) collectSlotSources(cells)
      } finally {
        restoreCurrentInstance(prevInner)
      }
      if (effect.active) {
        // a delivery that throws half-way is redone in full
        hasDelivered = false
        deliverInputs(
          instance,
          rawValues || (propsToUpdate && prevRawValues),
          propsToUpdate,
          cells,
        )
        hasDelivered = true
      }
    }, true)
    if (canRebind) instance.propsEffect = effect
    if (!prevEffect) {
      effect.run()
      // every getter and descriptor turned out to be constant
      if (!effect.deps && !canRebind) {
        effect.stop()
        instance.hasDynamicProps = false
      }
    } else {
      if (scope.flags & EffectFlags.PAUSED) effect.pause()
      effect.notify()
    }
  } finally {
    restoreCurrentInstance(prev)
  }
}

// One delivery: sync watchers run once the props and the descriptors are all
// written, and outside the input effect, which their callbacks must not
// subscribe.
export function deliverInputs(
  instance: VaporComponentInstance | undefined,
  rawValues: Record<string, any> | undefined,
  propsToUpdate?: unknown[],
  cells?: SlotSourceCell[],
): void {
  const prevSub = setActiveSub()
  startBatch()
  try {
    if (instance && rawValues) updateProps(instance, rawValues, propsToUpdate)
    if (cells) commitSlotSources(cells)
  } finally {
    try {
      endBatch()
    } finally {
      setActiveSub(prevSub)
    }
  }
}

export function collectSlotSources(cells: SlotSourceCell[]): void {
  for (let i = 0; i < cells.length; i++) {
    const cell = cells[i]
    cell.next = cell.source()
  }
}

// an unchanged descriptor keeps the identity its readers already saw
function commitSlotSources(cells: SlotSourceCell[]): void {
  for (let i = 0; i < cells.length; i++) {
    const cell = cells[i]
    const next = stabilizeDynamicSourceValue(cell.committed, cell.next!)
    if (hasChanged(next, cell.committed)) {
      cell.committed = next
      triggerDep(cell)
    }
  }
}

function hasDynamicPropsSource(rawProps: RawProps): boolean {
  if (rawProps.$) return true
  for (const key in rawProps) {
    if (isFunction(rawProps[key])) return true
  }
  return false
}

export function collectProps(
  rawProps: RawProps,
  prevStyle?: unknown,
): Record<string, any> {
  // Raw attrs may contain prototype-named keys such as __proto__.
  const rawValues: Record<string, any> = Object.create(null)
  const dynamicSources = rawProps.$ || EMPTY_ARR
  for (let i = -1; i < dynamicSources.length; i++) {
    const source = i < 0 ? rawProps : dynamicSources[i]
    const isDynamic = isFunction(source)
    const resolved = isDynamic ? source() : source
    for (const key in resolved) {
      if (i < 0 && key === '$') continue
      const value = isDynamic ? resolved[key] : readSource(resolved[key])
      if (!dynamicSources.length) {
        rawValues[key] = value
      } else if (key === 'class') {
        if (rawValues.class !== value) {
          rawValues.class = normalizeClass([rawValues.class, value])
        }
      } else if (key === 'style') {
        rawValues.style = normalizeStyle([rawValues.style, value])
      } else if (isOn(key)) {
        const existing = rawValues[key]
        if (
          value &&
          existing !== value &&
          !(isArray(existing) && existing.includes(value))
        ) {
          rawValues[key] = existing
            ? ([] as any[]).concat(existing, value)
            : value
        } else if (value == null && existing == null && !isModelListener(key)) {
          rawValues[key] = value
        }
      } else if (key !== '') {
        rawValues[key] = value
      }
    }
  }
  // merged sources are normalized above
  if (dynamicSources.length) {
    if (rawValues.style) {
      rawValues.style = stabilizeDynamicSourceValue(prevStyle, rawValues.style)
    }
  } else {
    if (rawValues.class) {
      rawValues.class = normalizePropValue('class', rawValues.class)
    }
    if (rawValues.style) {
      rawValues.style = normalizePropValue('style', rawValues.style, prevStyle)
    }
  }
  return rawValues
}

// The getters that changed against delivered raw values whose keys are
// static, as [key, value, …].
function collectPropsToUpdate(
  rawProps: RawProps,
  prevRawValues: Record<string, any>,
): unknown[] | undefined {
  let propsToUpdate: unknown[] | undefined
  for (const key in rawProps) {
    const source = rawProps[key]
    if (isFunction(source)) {
      const prevValue = prevRawValues[key]
      const value = normalizePropValue(key, source(), prevValue)
      if (hasChanged(value, prevValue)) {
        ;(propsToUpdate || (propsToUpdate = [])).push(key, value)
      }
    }
  }
  return propsToUpdate
}

// Writes one delivery into the instance; `deliverInputs` owns the batch and
// the untracked window around it.
function updateProps(
  instance: VaporComponentInstance,
  rawValues: Record<string, any>,
  // the entries to set on the delivered `rawValues`, as [key, value, …]
  propsToUpdate?: unknown[],
): void {
  const propsValues = instance.propsValues
  const [options, needCastKeys] = normalizePropsOptions(instance.type)
  const emitsOptions = normalizeEmitsOptions(instance.type)
  const prevRawValues = instance.rawValues
  // nothing is subscribed or left over before the first delivery
  const isInitial = prevRawValues === INITIAL_RAW_VALUES
  if (propsToUpdate) {
    for (let i = 0; i < propsToUpdate.length; i += 2) {
      rawValues[propsToUpdate[i] as string] = propsToUpdate[i + 1]
    }
  } else if (!isInitial) {
    rawValues = stabilizeDynamicSourceValue(prevRawValues, rawValues)
  }
  // Raw listeners become current before normalized keys notify watchers.
  instance.rawValues = rawValues
  if (propsToUpdate || (!isInitial && rawValues !== prevRawValues)) {
    triggerPropsValue(instance, RAW_VALUES_KEY)
  }
  const vnode = isInteropEnabled && instance.interopVNode
  if (vnode && vnode.vi) vnode.props = rawValues

  const present: Record<string, true> | undefined =
    propsToUpdate || isInitial ? undefined : Object.create(null)
  let rawCastValues: Record<string, unknown> | undefined
  const keys = propsToUpdate || Object.keys(rawValues)
  for (let i = 0; i < keys.length; i += propsToUpdate ? 2 : 1) {
    let key = keys[i] as string
    if (isReservedProp(key)) continue
    const value = rawValues[key]
    const camelKey = camelize(key)
    if (options && hasOwn(options, camelKey)) {
      key = camelKey
      if (needCastKeys && needCastKeys.includes(key)) {
        if (!rawCastValues) {
          rawCastValues = Object.create(null) as Record<string, unknown>
        }
        rawCastValues[key] = value
        continue
      }
    } else if (isEmitListener(emitsOptions, key)) {
      continue
    }
    if (present) present[key] = true
    setPropValue(instance, key, value, isInitial)
  }
  // after the ordinary props: a default factory may read them
  if (needCastKeys && (rawCastValues || !propsToUpdate)) {
    for (let i = 0; i < needCastKeys.length; i++) {
      const key = needCastKeys[i]
      const isAbsent = !rawCastValues || !hasOwn(rawCastValues, key)
      if (isAbsent && propsToUpdate) continue
      setPropValue(
        instance,
        key,
        resolvePropValue(
          options!,
          key,
          isAbsent ? undefined : rawCastValues![key],
          instance,
          resolveDefault,
          isAbsent,
        ),
        isInitial,
      )
      if (present) present[key] = true
    }
  }
  if (!propsToUpdate) {
    for (const key in options) {
      if (present ? !present[key] : !hasOwn(propsValues, key)) {
        setPropValue(
          instance,
          key,
          resolvePropValue(
            options,
            key,
            undefined,
            instance,
            resolveDefault,
            true,
          ),
          isInitial,
        )
        if (present) present[key] = true
      }
    }
    if (present) {
      for (const key in propsValues) {
        if (!present[key]) {
          delete propsValues[key]
          triggerPropsValue(instance, key)
          triggerPropsValue(instance, ATTR_KEYS)
        }
      }
    }
  }
  if (__DEV__ && options) {
    pushWarningContext(instance)
    try {
      validateProps(rawValues, instance.props, options)
    } finally {
      popWarningContext()
    }
  }
}

function setPropValue(
  instance: VaporComponentInstance,
  key: string,
  value: unknown,
  isInitial: boolean,
) {
  const propsValues = instance.propsValues
  if (isInitial) {
    propsValues[key] = value
    return
  }
  const hadKey = hasOwn(propsValues, key)
  const oldValue = propsValues[key]
  propsValues[key] = value
  if (!hadKey) {
    triggerPropsValue(instance, key)
    triggerPropsValue(instance, ATTR_KEYS)
  } else if (hasChanged(value, oldValue)) {
    triggerPropsValue(instance, key)
  }
}
