name: 'ci'
on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    branches:
      - main
      - minor
      - vapor

jobs:
  test:
    if: ${{ ! startsWith(github.event.head_commit.message, 'release:') && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) }}
    uses: ./.github/workflows/test.yml

  continuous-release:
    if: github.repository == 'vuejs/core' && github.ref_name != 'vapor'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false

      - name: Install deps
        run: vp install --frozen-lockfile

      - name: Build
        run: vp exec pnpm run build --withTypes

      - name: Release
        run: vpx pkg-pr-new publish --compact --pnpm './packages/*' --packageManager=pnpm,npm,yarn
