name: size data

on:
  push:
    branches:
      - main
      - minor
  pull_request:
    branches:
      - main
      - minor

permissions:
  contents: read

env:
  PUPPETEER_SKIP_DOWNLOAD: 'true'

jobs:
  upload:
    if: github.repository == 'vuejs/core'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - run: vp exec pnpm run size

      - name: Save PR number & base branch
        if: ${{github.event_name == 'pull_request'}}
        run: |
          echo ${{ github.event.number }} > ./temp/size/number.txt
          echo ${{ github.base_ref }} > ./temp/size/base.txt

      - name: Upload Size Data
        uses: actions/upload-artifact@v6
        with:
          name: size-data
          path: temp/size
