name: size data

on:
  push:
    branches:
      - main
      - minor
  pull_request:
    branches:
      - main
      - minor

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  PUPPETEER_SKIP_DOWNLOAD: 'true'

jobs:
  upload:
    if: github.repository == 'vuejs/core'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: '.node-version'
          cache: true

      - run: vp run size

      - name: Save PR number & base branch
        if: ${{github.event_name == 'pull_request'}}
        run: |
          echo ${{ github.event.number }} > ./temp/size/number.txt
          echo ${{ github.base_ref }} > ./temp/size/base.txt

      - name: Upload Size Data
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: size-data
          path: temp/size
