name: 'test'

on: workflow_call

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false

      - run: vp install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test-unit

  unit-test-windows:
    runs-on: windows-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false

      - run: vp install --frozen-lockfile

      - name: Run compiler unit tests
        run: pnpm run test-unit compiler

      - name: Run ssr unit tests
        run: pnpm run test-unit server-renderer

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup cache for Chromium binary
        uses: actions/cache@v5
        with:
          path: ~/.cache/puppeteer
          key: chromium-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false

      - run: vp install --frozen-lockfile
      - run: node node_modules/puppeteer/install.mjs

      - name: Run e2e tests
        run: pnpm run test-e2e

      - name: verify treeshaking
        run: node scripts/verify-treeshaking.js

  e2e-vapor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup cache for Chromium binary
        uses: actions/cache@v5
        with:
          path: ~/.cache/puppeteer
          key: chromium-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false

      - run: vp install --frozen-lockfile
      - run: node node_modules/puppeteer/install.mjs

      - name: Run e2e tests
        run: pnpm run test-e2e-vapor

  lint-and-test-dts:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false

      - run: vp install --frozen-lockfile

      - name: Run lint
        run: vp lint

      - name: Run format check
        run: vp fmt --check

      - name: Run type check
        run: pnpm run check

      - name: Run type declaration tests
        run: pnpm run test-dts
